apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
  labels:
    volume-type: ssd
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    namespace: default
    name: ebs-claim
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-013317e0e23ad6eb2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-east-2b